name: Build Dylib Only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Manual Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          mkdir -p ~/theos/sdks
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks/
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Build Dylib
        env:
          THEOS: /Users/runner/theos
        run: |
          make clean
          make FINALPACKAGE=1
          mkdir -p out
          find .theos/obj/ -name "WGEKeyboardFix.dylib" -exec cp {} out/WGEKeyboardFix.dylib \;

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WGEKeyboardFix-Dylib
          path: out/
